server:
  tomcat:
    max-http-form-post-size: 50MB
  compression:
    enabled: true
  port: 8000
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    time-zone: ${TZ:Asia/Shanghai}
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://${DB_HOST:172.16.10.50}:${DB_PORT:5432}/${DB_DATABASE:tongliaooj}?currentSchema=web_oj
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  redis:
    host: ${REDIS_HOST:172.16.10.50}
    password: ${REDIS_PASSWORD:redis}
    database: ${REDIS_DATABASE:2}
judge:
  server:
    host: ${JUDGE_HOST:172.16.10.50}
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
