services:
  web_oj:
    image: registry.cn-hangzhou.aliyuncs.com/wuluknut-ci/tongliao-oj:latest
    restart: always
    depends_on:
      - pgsql
      - redis
    ports:
      - 8000:8000
    networks:
      - bridge_network
    environment:
      - TZ=Asia/Shanghai
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - REDIS_PASSWORD=redis
  web_erupt:
    image: registry.cn-hangzhou.aliyuncs.com/wuluknut-ci/tongliao-oj:latest
    restart: always
    depends_on:
      - pgsql
      - redis
    ports:
      - 7000:7000
    networks:
      - bridge_network
    environment:
      - TZ=Asia/Shanghai
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - REDIS_PASSWORD=redis
    command: ./erupt-entrypoint.sh
  judge0_server:
    image: judge0/judge0:1.13.0
    restart: always
    privileged: true
    depends_on:
      - pgsql
      - redis
    expose:
      - 2358
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    networks:
      - bridge_network
  judge0_workers:
    image: judge0/judge0:1.13.0
    restart: always
    privileged: true
    depends_on:
      - pgsql
      - redis
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    networks:
      - bridge_network
    command: ./scripts/workers
  pgsql:
    image: postgres:16-alpine
    restart: always
    expose:
      - 5432
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    networks:
      - bridge_network
    environment:
      - TZ=Asia/Shanghai
    env_file: judge0.conf
  redis:
    image: redis:7-alpine
    restart: always
    expose:
      - 6379
    volumes:
      - ./data/redis:/data
    networks:
      - bridge_network
    environment:
      - TZ=Asia/Shanghai
    env_file: judge0.conf
    command: sh -c "redis-server --save 60 1 --loglevel warning --requirepass $$REDIS_PASSWORD"
networks:
  bridge_network:
