name: docker-image-push

on:
  push:
    tags:
      - v*

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PNPM 8
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up NodeJS 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache-dependency-path: '**/pnpm-lock.yaml'
          cache: 'pnpm'

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USER }}-ci/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{version}}

      - name: Build and push an Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64/v8
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
